### ISSUE TITLE
Typo (line unknown - before cell 9): "The Higgs boson analysis implemented here considers Higgs boson decays into a proton-proton pair. "

### ISSUE THREAD

**Issue by MidnightExcursion** [atlas-outreach-data-tools/notebooks-collection-opendata#31]
This is a Higgs decaying to a photon-photon pair, not proton-proton pair.

**Comment by artfisica** [comment]
can you point to the notebooks, please?

**Comment by MidnightExcursion** [comment]
> 

Yes, my apologies. Its title is "python_Hyy_channel.ipynb" that is featured in "ATLAS_OpenData__13-TeV_analysis_example". Line unknown, but the sentence before cell [9]: "...Higgs boson decays into a proton-proton pair."
