### ISSUE TITLE
UpROOT notebook HZZ_BDT.ipynb --> maybe an issue in MyBinder

### ISSUE THREAD

**Issue by artfisica** [atlas-outreach-data-tools/notebooks-collection-opendata#8]
Hi @meevans1,

I would like you to ask you to take a look at the notebook HZZ_BDT.ipynb.
I did a try in MyBinder and it breaks in Cell #12.

See below, please:

![Screenshot 2020-06-29 00 38 16](https://user-images.githubusercontent.com/8846121/85960091-161b9100-b9a1-11ea-9f34-2543b56660c0.png)

**Comment by meevans1** [comment]
Hi Arturo,

Sorry about this. It's because I hadn't changed from taking the input from my local repo, to the online repo in Cell #3. This should be fixed in Merge Request #9 

Thanks
Meirin

**Comment by artfisica** [comment]
Hi @meevans1,

Thank you.
I also repaired the name of the new package in enviroment.yml, to `scikit-learn`

Closing this issue.
